
remote_theme: "jeffreytse/jekyll-theme-yat"
title: Hoshuuzora
email: azzamimutahharialfarrah@gmail.com
author: Azzami Mutahhari
description: >-
  Tempat pelarian dikala tomi gabut gak ada kerjaan
yat:
  date_format: "%b %d, %Y"
header_pages:
   - index.html
   - archives.html
   - categories.html
   - tags.html
   - about.md
 defaults:
   home:
     heading: "Hoshuuzora"
     subheading: "Tempat pelarian dikala tomi gabut gak ada kerjaan"
